### ISSUE TITLE
关于DSO的实际运行的问题

### ISSUE THREAD

**Issue by RaymondChanSZU666** [DroidAITech/vslam-evaluation#2]
您好，我在用外接摄像头运行dso时移动稍微快一点程序就会崩掉，请问你有没有出现过这种情况啊？这种情况该怎么解决啊？谢谢

**Comment by brucetend** [comment]
我觉得是镜头移动快了，接触不良了

**Comment by RaymondChanSZU666** [comment]
> 我觉得是镜头移动快了，接触不良了

应该不是这个问题吧，我的镜头一直都是在工作的。

**Comment by anchuanxu** [comment]
您好 这个问题是多方面的

第一：您的外接摄像头输入分辨率和输出分辨率必须要有所落差，这样课已很大程度降低DSO崩掉的可能性，j建议输入1080*720 输出640*480 ；其次就是速度问题，不要瞬时移动速度过快，也容易引起DSO丢掉关键帧，位姿估计失败。

**Comment by RaymondChanSZU666** [comment]
> 您好 这个问题是多方面的
> 
> 第一：您的外接摄像头输入分辨率和输出分辨率必须要有所落差，这样课已很大程度降低DSO崩掉的可能性，j建议输入1080_720 输出640_480 ；其次就是速度问题，不要瞬时移动速度过快，也容易引起DSO丢掉关键帧，位姿估计失败。

您好，谢谢你的回答，但是我按你的建议尝试把输入改成1080 720输出为640 480 ，但是这样就不能够运行了，出现了段错误。

**Comment by anchuanxu** [comment]
>您好 这个问题是多方面的
第一：您的外接摄像头输入分辨率和输出分辨率必须要有所落差，这样课已很大程度降低DSO崩掉的可能性，j建议输入1080_720 输出640_480 ；其次就是速度问题，不要瞬时移动速度过快，也容易引起DSO丢掉关键帧，位姿估计失败。
您好，谢谢你的回答，但是我按你的建议尝试把输入改成1080 720输出为640 480 ，但是这样就不能够运行了，出现了段错误。

错误log可以po上来吗？

**Comment by RaymondChanSZU666** [comment]
> > 您好 这个问题是多方面的
> > 第一：您的外接摄像头输入分辨率和输出分辨率必须要有所落差，这样课已很大程度降低DSO崩掉的可能性，j建议输入1080_720 输出640_480 ；其次就是速度问题，不要瞬时移动速度过快，也容易引起DSO丢掉关键帧，位姿估计失败。
> > 您好，谢谢你的回答，但是我按你的建议尝试把输入改成1080 720输出为640 480 ，但是这样就不能够运行了，出现了段错误。
> 
> 错误log可以po上来吗？

`NO PHOTOMETRIC Calibration!
Reading Photometric Calibration from file
PhotometricUndistorter: Could not open file!
using pyramid levels 0 to 3. coarsest resolution: 80 x 60!
START PANGOLIN!
Undistort::undistort: wrong image size (640 480 instead of 640 480)
段错误 (核心已转储)`

它最后输出这些

**Comment by anchuanxu** [comment]
> > > 您好 这个问题是多方面的
> > > 第一：您的外接摄像头输入分辨率和输出分辨率必须要有所落差，这样课已很大程度降低DSO崩掉的可能性，j建议输入1080_720 输出640_480 ；其次就是速度问题，不要瞬时移动速度过快，也容易引起DSO丢掉关键帧，位姿估计失败。
> > > 您好，谢谢你的回答，但是我按你的建议尝试把输入改成1080 720输出为640 480 ，但是这样就不能够运行了，出现了段错误。
> > 
> > 
> > 错误log可以po上来吗？
> 
> `NO PHOTOMETRIC Calibration! Reading Photometric Calibration from file PhotometricUndistorter: Could not open file! using pyramid levels 0 to 3. coarsest resolution: 80 x 60! START PANGOLIN! Undistort::undistort: wrong image size (640 480 instead of 640 480) 段错误 (核心已转储)`
> 
> 它最后输出这些

这个错误好像还是说标定文件格式有问题，你可以检查一下，下面我会放上我的标定文件

**Comment by anchuanxu** [comment]
```
949.986527 947.609436  633.906959 367.183306  0.178151 -0.290003 0.011788 -0.007432 
1280 720
crop
640 480

```

**Comment by RaymondChanSZU666** [comment]
> ```
> 949.986527 947.609436  633.906959 367.183306  0.178151 -0.290003 0.011788 -0.007432 
> 1280 720
> crop
> 640 480
> ```



> ```
> 949.986527 947.609436  633.906959 367.183306  0.178151 -0.290003 0.011788 -0.007432 
> 1280 720
> crop
> 640 480
> ```

您好，我只有用官方原来的标定文件才能运行。
不知道您能否加一下我的qq呢？有些问题想请教你
765886113  十分感谢您

**Comment by lazyparser** [comment]
> > ```
> > 949.986527 947.609436  633.906959 367.183306  0.178151 -0.290003 0.011788 -0.007432 
> > 1280 720
> > crop
> > 640 480
> > ```
> 
> > ```
> > 949.986527 947.609436  633.906959 367.183306  0.178151 -0.290003 0.011788 -0.007432 
> > 1280 720
> > crop
> > 640 480
> > ```
> 
> 您好，我只有用官方原来的标定文件才能运行。
> 不知道您能否加一下我的qq呢？有些问题想请教你
> 765886113 十分感谢您

一般只在公开领域讨论，讨论的内容可以作为后续同学的参考。GitHub或者 q.droid.ac.cn 都可以。我们有顾问在这两个地方回复。

公司员工和签约顾问的私下讨论是要付费的，没有免费的一对一讨论😁

非公司员工/顾问/实习生不在收费的范围内，可以自行联系一起学习进步（不过，还是希望可以讲讨论内容分享出来）。

**Comment by anchuanxu** [comment]
> > > ```
> > > 949.986527 947.609436  633.906959 367.183306  0.178151 -0.290003 0.011788 -0.007432 
> > > 1280 720
> > > crop
> > > 640 480
> > > ```
> > 
> > 
> > > ```
> > > 949.986527 947.609436  633.906959 367.183306  0.178151 -0.290003 0.011788 -0.007432 
> > > 1280 720
> > > crop
> > > 640 480
> > > ```
> > 
> > 
> > 您好，我只有用官方原来的标定文件才能运行。
> > 不知道您能否加一下我的qq呢？有些问题想请教你
> > 765886113 十分感谢您
> 
> 一般只在公开领域讨论，讨论的内容可以作为后续同学的参考。GitHub或者 q.droid.ac.cn 都可以。我们有顾问在这两个地方回复。
> 
> 公司员工和签约顾问的私下讨论是要付费的，没有免费的一对一讨论
> 
> 非公司员工/顾问/实习生不在收费的范围内，可以自行联系一起学习进步（不过，还是希望可以讲讨论内容分享出来）。

上述同学问题已解决,主要是相机标定的问题.
